apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: local-dev
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: RedisHost
      key:  RedisHost
  - name: redisPassword
    secretKeyRef:
      name: RedisPassword
      key:  RedisPassword
auth:
  secretStore: secret-store