apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store
  namespace: local-dev
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: C:\Users\ricopegnata\source\repos\DaprMicroservicesTest\dapr\components\developmet_secrets.json
  - name: nestedSeparator
    value: ":"
