apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store
  namespace: production
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName # Required
    value: "[key_vault_name]"
  - name: azureTenantId
    value: "[your_tenant_id]"
  - name: azureClientId
    value: "[your_service_principal_app_id]"
  - name: azureClientSecret
    value : "[your_service_principal_app_id]"