apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store
  namespace: production
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName # Required
    value: dapr-test
  - name: azureTenantId
    value: "c4e1aa87-1445-4eb0-8b01-4f4fa9420510"
  - name: azureClientId
    value: "[your_service_principal_app_id]"
  - name: azureCertificateFile
    value : "[pfx_certificate_file_fully_qualified_local_path]"